### ISSUE TITLE
USER STORY: Site security

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/e-commerce#18]
As a **Site Owner / User** I can **be confident of the sites security** so that **I think all data will be secure**

# Acceptance Criteria

 - No passwords are in the repo
 - All secret keys are hidden in env var's or the files are in .gitignore
 - DEBUG is turned off before final deployment
 - Non-admin users cannot access the data store directly without going through the code

# Tasks

- [ ] Make sure no passwords are in the repo
- [ ] Make sure all secret keys are hidden in env var's or the files are in .gitignore
- [ ] Make sure non-admin users cannot access the data store directly CHANGE THIS TO HOW THIS IS DONE
- [ ] Turn off DEBUG before final deployment
- [ ] Log in is role-based CHANGE THIS TO HOW THIS IS DONE
