### ISSUE TITLE
USER STORY: Delete personal details

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/e-commerce#30]
As a **Site User** I can **delete my personal details** so that **they are no longer stored by the site**

# Acceptance Criteria

- If previously saved, I can delete my personal details
- I have to confirm I want to delete my details before they are deleted
  

# Tasks

- [ ] Add a delete button to the relevant page
- [ ] Add delete confirmation
- [ ] Manually test editing personal details
