### ISSUE TITLE
USER STORY: Delete product from site

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/e-commerce#36]
As a **Site Owner** I can **delete products from the site** so that **goods can be removed from being able to be purchased**

# Acceptance Criteria

 - I can delete products from the site 
 - I am asked to confirm if I want to delete the product

# Tasks

- [ ] Create a delete button
- [ ] Create confirm delete section 
- [ ] Implement product deletion
