### ISSUE TITLE
USER STORY: Edit products on site

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/e-commerce#37]
As a **Site Owner** I can **edit products on the site** so that **any mistakes can be corrected or changes made**

# Acceptance Criteria

 - I can edit products on the site 
 - I am asked to confirm if the edit is correct

# Tasks

- [ ] Use add product table to edit products
- [ ] Create confirmation page
- [ ] Implement editing product info
